### ISSUE TITLE
v1.0.0-rc26中 Sora.Net.ConnectionManager.HeartBeatUpdate() 抛出 KeyNotFoundException

### ISSUE THREAD

**Issue by Awbugl** [DeepOceanSoft/Sora#48]
**使用环境**
 -  框架版本号:`v1.0.0-rc26` [7bccd2baf0](https://github.com/DeepOceanSoft/Sora/tree/7bccd2baf062d54bf77885445b4469475d0dbeea)
 -  运行环境:`Windows Server 2019 Datacenter, .NET SDK 5.0.404`

**bug描述及如何复现**
项目使用 SoraServiceFactory.CreateMultiService() 创建多个Sora服务实例
通过反向ws与多个go-cqhttp服务通讯
启动Sora约五分钟后 Sora.Net.ConnectionManager.HeartBeatUpdate() 抛出KeyNotFoundException

**错误截图或日志**
2022/1/2 14:39:49
System.Collections.Generic.KeyNotFoundException: The given key 'ced23f42-38af-4544-a057-79592660966c' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at Sora.Net.ConnectionManager.HeartBeatUpdate(Guid connectionGuid) in ..\Sora\Net\ConnectionManager.cs:line 177
   at Sora.OnebotInterface.EventInterface.MetaAdapter(JObject messageJson, Guid connection) in ..\Sora\OnebotInterface\EventInterface.cs:line 314
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Awbugl** [comment]
啊打错了 是rc36

**Comment by Yukari316** [comment]
这个似乎是老版本已知的bug
在较新的版本中应该是修复掉了的

**Comment by Awbugl** [comment]
好的 谢谢啦 我再仔细看看commit

**Comment by Yukari316** [comment]
不谢哟，还有就是因为这个库正常来说都是我一个人维护，所以旧版本的问题一般是不会管的（
