### ISSUE TITLE
单条信息同时匹配多个指令时，eventArgs.CommandRegex永远是最后匹配Command的正则

### ISSUE THREAD

**Issue by NepPure** [DeepOceanSoft/Sora#59]
**使用环境**
 -  框架版本号:
<img width="131" alt="image" src="https://user-images.githubusercontent.com/12379907/169792783-ea988606-5eaa-469e-9d40-be6d12ee1add.png">

 -  运行环境:`net6`

**bug描述**
单条信息触发多个`Command`时会共享`args`上下文实例，导致正则匹配模式，`eventArgs.CommandRegex`匹配到的正则永远是最后一个`Command`的

**如何复现**

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/12379907/169793364-4cd5adce-a1c7-4293-b8aa-6f15d880084a.png">

类似这样，在其他命令里面，`eventArgs.CommandRegex`都是`.*`

**Comment by NepPure** [comment]
```
Application: FFXIV.Sora.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Sora.Command.CommandManager.<>c__DisplayClass21_0.<CommandAdapter>b__10(RegexCommandInfo cmd)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Sora.Command.CommandManager.CommandAdapter(BaseMessageEventArgs eventArgs)
   at Sora.OnebotAdapter.EventAdapter.MessageAdapter(JObject messageJson, Guid connection)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

```
