### ISSUE TITLE
Fatal：System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by NepPure** [DeepOceanSoft/Sora#62]
rc.54

稳定跑了一个月，今天挂了

```
Application: FFXIV.Sora.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key '41309edd-e531-4a8d-82c6-ac9d7c1a0faf' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at Sora.EventArgs.SoraEvent.BaseMessageEventArgs..ctor(Guid serviceId, Guid connectionId, String eventName, BaseObMessageEventArgs msg, SourceFlag source)
   at Sora.OnebotAdapter.EventAdapter.MessageAdapter(JObject messageJson, Guid connection)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


```

**Comment by Yukari316** [comment]
暂时修复了一下这个问题（大概）
触发可能是因为GC回收了服务造成的，可能就算修复了这个bug也有可能造成外部逻辑的错误

**Comment by NepPure** [comment]
```
Application: FFXIV.Sora.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key '10f27201-b1c0-43d3-8812-72c68bf549f4' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at Sora.EventArgs.SoraEvent.BaseMessageEventArgs..ctor(Guid serviceId, Guid connectionId, String eventName, BaseObMessageEventArgs msg, SourceFlag source)
   at Sora.OnebotAdapter.EventAdapter.MessageAdapter(JObject messageJson, Guid connection)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

```

更新后还是寄了

**Comment by NepPure** [comment]
https://github.com/DeepOceanSoft/Sora/blob/de07ac1b45d3f5ce256c389fc7d341703386ab88/Sora/EventArgs/SoraEvent/BaseMessageEventArgs.cs#L66

这个不存在，除了Dispose 有无其他可能性

**Comment by Yukari316** [comment]
除了被GC Dispose，不太可能是其他的问题

如果你的代码里没有调用过Dispose，只可能是被GC回收了
感觉有可能是其他的业务代码触发了奇怪的bug，导致GC执行了回收
